apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myapp

resources:
- deployment-blue.yaml
- service.yaml

commonLabels:
  app: myapp
  managed-by: kustomize

images:
- name: myapp
  newTag: latest

# Uncomment to switch to green deployment
# patchesStrategicMerge:
# - patch-green.yaml