apiVersion: v1
kind: Service
metadata:
  name: vle7-app-service
  labels:
    app: vle7-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: vle7-app
    version: blue  # Default to blue, change to green for traffic switch